### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by coutouly** [surrealdb/surrealist#147]
**Describe the bug**
here is a working dockerfile maybe you help me improve it

**To Reproduce**
```
FROM archlinux

RUN pacman -Sy --needed git xorg-server-xvfb base-devel webkit2gtk rust npm nodejs --noconfirm


WORKDIR /app
RUN git clone https://github.com/StarlaneStudios/Surrealist.git

WORKDIR /app/Surrealist
RUN npm i  pnpm
RUN sed -i '/port: 1420/i\    host: true,' vite.config.ts
CMD ["xvfb-run", "npm", "run", "tauri:dev"]
EXPOSE  1420
```

**Expected behavior**
docker build .
docker run 

**Environment (you can view the current version under Settings):**

**Comment by ravensorb** [comment]
Would be great to see a standard docker image that could be used to deploy along with SurrealDb for development purposes.

**Comment by macjuul** [comment]
I'm struggling to see the necessity of a docker image considering Surrealist can already be accessed universally as a web app (surrealist.app), or installed locally as desktop app. Which benefits will a docker image provide over the existing deployment targets?

**Comment by OmanF** [comment]
@macjuul, while I haven't tried the Docker approach yet, I can think of a couple of reasons:

* Web UI - The `SurrealDB` team themselves, on the official documentation, admit the web UI has several setbacks, security-wise, that make it inferior to the installed app.
* That, in itself, pushing you towards an installed app, is something I don't like, especially as the installed app is native, i.e. **not** one of the condensed platforms (`Flatpak`, `AppImage`, etc.)
* Also, as the issue board shows, the web UI has several outstanding **showstopper** issues at the moment, making using it nearly impossible.
* Installed app - As the issue board itself shows, the installed **native app** is also nearly useless on some platforms - seems the only platform that **doesn't** have issues is `macOS` (how very surprising`</endCynicism>`).
* As I mentioned earlier, if forced to have a local instance, I'd rather have it in one of the condensed, writing-limited-to-its-sandbox, app formats, not one that has access to every bit, literally, of my machine.

I'm not arguing these reasons are valid enough to merit an official Docker image, but if I were part of `SurrealDB` team, I would **not** dismiss it out of hand, either.

Unfortunately, for a production-ready app, `Surrealist`, on all platforms but `macOS` is... **not**.
Having an **official**, **working**, Docker image will go a long way towards `SurrealDB`, and `Surrealist`'s image, pun intended, which at the moment is not great... and I'm saying this as someone who is following the whole `Surreal*` ecosystem since it was v0.9.

**Comment by Zercerium** [comment]
It would be a benefit to deploy your own instance, so that you don't have to rely on the web app and you have the control about what is running. Also not everyone need to install a separate app and keep it updated.

I would be nice to have something like pgadmin for surrealDB, which could be surrealist.

**Comment by coutouly** [comment]
Hello
I saw the site surrealist.app and i want to install the same as you did.
I cant use surréaliste.app because i work behind firewall.

**Comment by macjuul** [comment]
Thanks for the feedback everyone! I hear you, and will spend some time researching the viability of publishing an official docker image in the near future

**Comment by ivs** [comment]
This one for webapp hosting:
```
FROM node

RUN npm i -g pnpm

WORKDIR /app
COPY . /app

RUN pnpm install && pnpm run build

EXPOSE 1420

ENTRYPOINT [ "pnpm", "run", "start", "--host" ]
```

And compose like this(with traefik)
```
  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start --auth -u root -p root tikv://pd:2379
    depends_on:
      - "tikv"
    labels:
      - traefik.http.routers.surrealdb.rule=Host(`surrealdb.domain`)
      - traefik.http.services.surrealdb.loadbalancer.server.port=8000
      - traefik.http.routers.surrealdb.entrypoints=websecure
      - traefik.http.routers.surrealdb.tls=true

  surrealist:
    image: surrealist
    labels:
      - traefik.http.routers.surrealist.rule=Host(`surrealist.domain`)
      - traefik.http.services.surrealist.loadbalancer.server.port=1420
      - traefik.http.routers.surrealist.entrypoints=websecure
      - traefik.http.routers.surrealist.tls=true
      - traefik.http.routers.portainer.middlewares=auth
```
It seems that surrealist access db thru a browser, doesn't work for compose hosts.
