### ISSUE TITLE
Surrealist doesn't seem to work with default Docker Hub SurrealDB on Firefox

### ISSUE THREAD

**Issue by TimMensch** [surrealdb/surrealist#285]
**Describe the bug**
In Firefox, Surrealist can't connect to a SurrealDB server that _doesn't_ have https/wss certs installed. At first I thought it just didn't work at all, but further testing shows it works in Chrome; still, it shouldn't be hard to get it working everywhere so that users don't end up with a bad first experience of using Surrealist, right?

**To Reproduce**

I ran SurrealDB from a Docker Compose as follows:

```yaml
services:
  surrealdb:
    env_file:
      - path: ./.env
    entrypoint:
      - /surreal
      - start
      - --auth
      - -l
      - debug
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
```

The `.env` file has the USER/PASS, which I was able to verify worked by connecting to SurrealDB via the CLI.

Going to `localhost:8000` sends me to the Surrealist front page (which I'm guessing is to be expected?). I then set a new connection up as follows:

![image](https://github.com/surrealdb/surrealist/assets/530873/fbce34cc-8509-4ffc-8cc3-5229db135534)

Surrealist then starts out fine by getting the version # via ws://localhost:8000, but looking at the network panel it immediately upgrades to wss://localhost:8000, and then gets an error:

![image](https://github.com/surrealdb/surrealist/assets/530873/a873aa5a-fe94-4ada-b488-6c4e84a1966e)

**Expected behavior**
For it to work in Firefox? Sites that fail only in Firefox are pretty rare these days, and so it felt like Surrealist just Didn't Work. Only as I was typing in the above did I think to try it in Chrome, where it ... sort-of works. The designer keeps leaving extra lines all over the place until I refresh the screen entirely. 

**Environment:**
```
Platform: Web
Navigator: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0
Version: 2.0.6
Flags: featureFlags: false, models_view: true, apidocs_view: true, themes: false, newsfeed: true
```
